name: Integration Check

on:
push:
 branches: [ main, develop ]
pull_request:
 branches: [ main, develop ]

jobs:
integration-check:
 runs-on: ubuntu-latest
 
 steps:
 - uses: actions/checkout@v3
 - name: Set up Python
   uses: actions/setup-python@v4
   with:
     python-version: '3.10'
 - name: Install dependencies
   run: |
     python -m pip install --upgrade pip
     pip install -r requirements-dev.txt
 - name: Run integration tests
   run: |
     pytest tests/integration/ --cov=app
 - name: Check component interfaces
   run: |
     python tools/integration_monitor/compatibility_checker.py
